name: Build and Release workflow

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build scripts
        run: pnpm run build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/giveaways.user.js
            dist/giveaways.mini.user.js
