name: Build and Release workflow

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      script_path: ${{ steps.build_script.outputs.script_path }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build script
        run: |
          npm run build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/giveaways.user.js
            giveaways.json
